/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import '@stencil/router';
import '@stencil/state-tunnel';
import {
  AuthService,
} from './services/auth';
import {
  DatabaseService,
} from './services/database';
import {
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AdvRangerList {
    'auth': AuthService;
    'db': DatabaseService;
  }
  interface AdvRangerListAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
    'db'?: DatabaseService;
  }

  interface TrackerApp {
    'history': RouterHistory;
  }
  interface TrackerAppAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface TrackerHome {
    'auth': AuthService;
  }
  interface TrackerHomeAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
  }

  interface TrackerLoginItem {
    'Auth': AuthService;
    'authorized': boolean;
  }
  interface TrackerLoginItemAttributes extends StencilHTMLAttributes {
    'Auth'?: AuthService;
    'authorized'?: boolean;
    'onAuthClicked'?: (event: CustomEvent) => void;
  }

  interface TrackerLogin {
    'auth': AuthService;
  }
  interface TrackerLoginAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
  }

  interface TrackerPlanner {
    'auth': AuthService;
    'db': DatabaseService;
  }
  interface TrackerPlannerAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
    'db'?: DatabaseService;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdvRangerList': Components.AdvRangerList;
    'TrackerApp': Components.TrackerApp;
    'TrackerHome': Components.TrackerHome;
    'TrackerLoginItem': Components.TrackerLoginItem;
    'TrackerLogin': Components.TrackerLogin;
    'TrackerPlanner': Components.TrackerPlanner;
  }

  interface StencilIntrinsicElements {
    'adv-ranger-list': Components.AdvRangerListAttributes;
    'tracker-app': Components.TrackerAppAttributes;
    'tracker-home': Components.TrackerHomeAttributes;
    'tracker-login-item': Components.TrackerLoginItemAttributes;
    'tracker-login': Components.TrackerLoginAttributes;
    'tracker-planner': Components.TrackerPlannerAttributes;
  }


  interface HTMLAdvRangerListElement extends Components.AdvRangerList, HTMLStencilElement {}
  var HTMLAdvRangerListElement: {
    prototype: HTMLAdvRangerListElement;
    new (): HTMLAdvRangerListElement;
  };

  interface HTMLTrackerAppElement extends Components.TrackerApp, HTMLStencilElement {}
  var HTMLTrackerAppElement: {
    prototype: HTMLTrackerAppElement;
    new (): HTMLTrackerAppElement;
  };

  interface HTMLTrackerHomeElement extends Components.TrackerHome, HTMLStencilElement {}
  var HTMLTrackerHomeElement: {
    prototype: HTMLTrackerHomeElement;
    new (): HTMLTrackerHomeElement;
  };

  interface HTMLTrackerLoginItemElement extends Components.TrackerLoginItem, HTMLStencilElement {}
  var HTMLTrackerLoginItemElement: {
    prototype: HTMLTrackerLoginItemElement;
    new (): HTMLTrackerLoginItemElement;
  };

  interface HTMLTrackerLoginElement extends Components.TrackerLogin, HTMLStencilElement {}
  var HTMLTrackerLoginElement: {
    prototype: HTMLTrackerLoginElement;
    new (): HTMLTrackerLoginElement;
  };

  interface HTMLTrackerPlannerElement extends Components.TrackerPlanner, HTMLStencilElement {}
  var HTMLTrackerPlannerElement: {
    prototype: HTMLTrackerPlannerElement;
    new (): HTMLTrackerPlannerElement;
  };

  interface HTMLElementTagNameMap {
    'adv-ranger-list': HTMLAdvRangerListElement
    'tracker-app': HTMLTrackerAppElement
    'tracker-home': HTMLTrackerHomeElement
    'tracker-login-item': HTMLTrackerLoginItemElement
    'tracker-login': HTMLTrackerLoginElement
    'tracker-planner': HTMLTrackerPlannerElement
  }

  interface ElementTagNameMap {
    'adv-ranger-list': HTMLAdvRangerListElement;
    'tracker-app': HTMLTrackerAppElement;
    'tracker-home': HTMLTrackerHomeElement;
    'tracker-login-item': HTMLTrackerLoginItemElement;
    'tracker-login': HTMLTrackerLoginElement;
    'tracker-planner': HTMLTrackerPlannerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
