/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import '@stencil/router';
import '@stencil/state-tunnel';
import 'ionicons';
import {
  AuthService,
} from './services/auth';
import {
  DatabaseService,
} from './services/Firestore';
import {
  DatabaseService as DatabaseService2,
} from './services/Database';


export namespace Components {

  interface AdvGroupTab {
    'adventure': boolean | undefined | null;
    'discovery': boolean | undefined | null;
    'expedition': boolean | undefined | null;
    'kids': boolean | undefined | null;
  }
  interface AdvGroupTabAttributes extends StencilHTMLAttributes {
    'adventure'?: boolean | undefined | null;
    'discovery'?: boolean | undefined | null;
    'expedition'?: boolean | undefined | null;
    'kids'?: boolean | undefined | null;
  }

  interface AdvRangerGroups {
    'auth': AuthService;
    'db': DatabaseService;
  }
  interface AdvRangerGroupsAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
    'db'?: DatabaseService;
  }

  interface TrackerApp {}
  interface TrackerAppAttributes extends StencilHTMLAttributes {}

  interface TrackerHome {}
  interface TrackerHomeAttributes extends StencilHTMLAttributes {}

  interface TrackerLoginItem {
    'Auth': AuthService;
    'authorized': boolean;
  }
  interface TrackerLoginItemAttributes extends StencilHTMLAttributes {
    'Auth'?: AuthService;
    'authorized'?: boolean;
    'onAuthClicked'?: (event: CustomEvent) => void;
  }

  interface TrackerLogin {
    'auth': AuthService;
  }
  interface TrackerLoginAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
  }

  interface TrackerPlannerCheckboxItem {
    'id': string | null;
    'items': any;
    'label': string;
  }
  interface TrackerPlannerCheckboxItemAttributes extends StencilHTMLAttributes {
    'id'?: string | null;
    'items'?: any;
    'label'?: string;
  }

  interface TrackerPlannerDateItem {
    'id': string;
    'label': string;
  }
  interface TrackerPlannerDateItemAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'label'?: string;
  }

  interface TrackerPlannerSegmentItem {
    'id': string;
    'items': any;
  }
  interface TrackerPlannerSegmentItemAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'items'?: any;
    'onTrackerSegmentChange'?: (event: CustomEvent) => void;
  }

  interface TrackerPlannerSelectItem {
    'id': string;
    'items': any;
    'label': string;
  }
  interface TrackerPlannerSelectItemAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'items'?: any;
    'label'?: string;
    'onTrackerSelectChange'?: (event: CustomEvent) => void;
  }

  interface TrackerPlanner {
    'auth': AuthService;
    'db': DatabaseService;
  }
  interface TrackerPlannerAttributes extends StencilHTMLAttributes {
    'auth'?: AuthService;
    'db'?: DatabaseService;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdvGroupTab': Components.AdvGroupTab;
    'AdvRangerGroups': Components.AdvRangerGroups;
    'TrackerApp': Components.TrackerApp;
    'TrackerHome': Components.TrackerHome;
    'TrackerLoginItem': Components.TrackerLoginItem;
    'TrackerLogin': Components.TrackerLogin;
    'TrackerPlannerCheckboxItem': Components.TrackerPlannerCheckboxItem;
    'TrackerPlannerDateItem': Components.TrackerPlannerDateItem;
    'TrackerPlannerSegmentItem': Components.TrackerPlannerSegmentItem;
    'TrackerPlannerSelectItem': Components.TrackerPlannerSelectItem;
    'TrackerPlanner': Components.TrackerPlanner;
  }

  interface StencilIntrinsicElements {
    'adv-group-tab': Components.AdvGroupTabAttributes;
    'adv-ranger-groups': Components.AdvRangerGroupsAttributes;
    'tracker-app': Components.TrackerAppAttributes;
    'tracker-home': Components.TrackerHomeAttributes;
    'tracker-login-item': Components.TrackerLoginItemAttributes;
    'tracker-login': Components.TrackerLoginAttributes;
    'tracker-planner-checkbox-item': Components.TrackerPlannerCheckboxItemAttributes;
    'tracker-planner-date-item': Components.TrackerPlannerDateItemAttributes;
    'tracker-planner-segment-item': Components.TrackerPlannerSegmentItemAttributes;
    'tracker-planner-select-item': Components.TrackerPlannerSelectItemAttributes;
    'tracker-planner': Components.TrackerPlannerAttributes;
  }


  interface HTMLAdvGroupTabElement extends Components.AdvGroupTab, HTMLStencilElement {}
  var HTMLAdvGroupTabElement: {
    prototype: HTMLAdvGroupTabElement;
    new (): HTMLAdvGroupTabElement;
  };

  interface HTMLAdvRangerGroupsElement extends Components.AdvRangerGroups, HTMLStencilElement {}
  var HTMLAdvRangerGroupsElement: {
    prototype: HTMLAdvRangerGroupsElement;
    new (): HTMLAdvRangerGroupsElement;
  };

  interface HTMLTrackerAppElement extends Components.TrackerApp, HTMLStencilElement {}
  var HTMLTrackerAppElement: {
    prototype: HTMLTrackerAppElement;
    new (): HTMLTrackerAppElement;
  };

  interface HTMLTrackerHomeElement extends Components.TrackerHome, HTMLStencilElement {}
  var HTMLTrackerHomeElement: {
    prototype: HTMLTrackerHomeElement;
    new (): HTMLTrackerHomeElement;
  };

  interface HTMLTrackerLoginItemElement extends Components.TrackerLoginItem, HTMLStencilElement {}
  var HTMLTrackerLoginItemElement: {
    prototype: HTMLTrackerLoginItemElement;
    new (): HTMLTrackerLoginItemElement;
  };

  interface HTMLTrackerLoginElement extends Components.TrackerLogin, HTMLStencilElement {}
  var HTMLTrackerLoginElement: {
    prototype: HTMLTrackerLoginElement;
    new (): HTMLTrackerLoginElement;
  };

  interface HTMLTrackerPlannerCheckboxItemElement extends Components.TrackerPlannerCheckboxItem, HTMLStencilElement {}
  var HTMLTrackerPlannerCheckboxItemElement: {
    prototype: HTMLTrackerPlannerCheckboxItemElement;
    new (): HTMLTrackerPlannerCheckboxItemElement;
  };

  interface HTMLTrackerPlannerDateItemElement extends Components.TrackerPlannerDateItem, HTMLStencilElement {}
  var HTMLTrackerPlannerDateItemElement: {
    prototype: HTMLTrackerPlannerDateItemElement;
    new (): HTMLTrackerPlannerDateItemElement;
  };

  interface HTMLTrackerPlannerSegmentItemElement extends Components.TrackerPlannerSegmentItem, HTMLStencilElement {}
  var HTMLTrackerPlannerSegmentItemElement: {
    prototype: HTMLTrackerPlannerSegmentItemElement;
    new (): HTMLTrackerPlannerSegmentItemElement;
  };

  interface HTMLTrackerPlannerSelectItemElement extends Components.TrackerPlannerSelectItem, HTMLStencilElement {}
  var HTMLTrackerPlannerSelectItemElement: {
    prototype: HTMLTrackerPlannerSelectItemElement;
    new (): HTMLTrackerPlannerSelectItemElement;
  };

  interface HTMLTrackerPlannerElement extends Components.TrackerPlanner, HTMLStencilElement {}
  var HTMLTrackerPlannerElement: {
    prototype: HTMLTrackerPlannerElement;
    new (): HTMLTrackerPlannerElement;
  };

  interface HTMLElementTagNameMap {
    'adv-group-tab': HTMLAdvGroupTabElement
    'adv-ranger-groups': HTMLAdvRangerGroupsElement
    'tracker-app': HTMLTrackerAppElement
    'tracker-home': HTMLTrackerHomeElement
    'tracker-login-item': HTMLTrackerLoginItemElement
    'tracker-login': HTMLTrackerLoginElement
    'tracker-planner-checkbox-item': HTMLTrackerPlannerCheckboxItemElement
    'tracker-planner-date-item': HTMLTrackerPlannerDateItemElement
    'tracker-planner-segment-item': HTMLTrackerPlannerSegmentItemElement
    'tracker-planner-select-item': HTMLTrackerPlannerSelectItemElement
    'tracker-planner': HTMLTrackerPlannerElement
  }

  interface ElementTagNameMap {
    'adv-group-tab': HTMLAdvGroupTabElement;
    'adv-ranger-groups': HTMLAdvRangerGroupsElement;
    'tracker-app': HTMLTrackerAppElement;
    'tracker-home': HTMLTrackerHomeElement;
    'tracker-login-item': HTMLTrackerLoginItemElement;
    'tracker-login': HTMLTrackerLoginElement;
    'tracker-planner-checkbox-item': HTMLTrackerPlannerCheckboxItemElement;
    'tracker-planner-date-item': HTMLTrackerPlannerDateItemElement;
    'tracker-planner-segment-item': HTMLTrackerPlannerSegmentItemElement;
    'tracker-planner-select-item': HTMLTrackerPlannerSelectItemElement;
    'tracker-planner': HTMLTrackerPlannerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
